name: Docker Image CI

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

env:
  TARGET: debian

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get current date and version
        id: version
        run: |
          echo "date=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_OUTPUT
          echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push lsalpine
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            smhrambo/briar-mailbox:latest
            smhrambo/briar-mailbox:v1.0.8
            smhrambo/briar-mailbox:v1.0
            smhrambo/briar-mailbox:v1.0.8-lsalpine
            smhrambo/briar-mailbox:v1.0-lsalpine
            smhrambo/briar-mailbox:lsalpine
            smhrambo/briar-mailbox:ls
            smhrambo/briar-mailbox:v1.0.8-lsalpine3.20
            smhrambo/briar-mailbox:v1.0-lsalpine3.20
            smhrambo/briar-mailbox:lsalpine3.20, ls3.20
          platforms: |
            linux/amd64
            linux/arm64
          build-args: |
            BUILD_DATE=${{ steps.version.outputs.date }}
            BUILD_VERSION=${{ steps.version.outputs.hash }}
          target: lsalpine

      - name: Build and push lsdebian
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            smhrambo/briar-mailbox:v1.0.8-lsdebian
            smhrambo/briar-mailbox:v1.0-lsdebian
            smhrambo/briar-mailbox:lsdebian
            smhrambo/briar-mailbox:v1.0.8-lsbookworm
            smhrambo/briar-mailbox:v1.0-lsbookworm
            smhrambo/briar-mailbox:lsbookworm
          platforms: |
            linux/amd64
            linux/arm64
          build-args: |
            BUILD_DATE=${{ steps.version.outputs.date }}
            BUILD_VERSION=${{ steps.version.outputs.hash }}
          target: lsdebian

      - name: Build and push lsubuntu
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            smhrambo/briar-mailbox:v1.0.8-lsubuntu
            smhrambo/briar-mailbox:v1.0-lsubuntu
            smhrambo/briar-mailbox:lsubuntu
            smhrambo/briar-mailbox:v1.0.8-lsnoble
            smhrambo/briar-mailbox:v1.0-lsnoble
            smhrambo/briar-mailbox:lsnoble
          platforms: |
            linux/amd64
            linux/arm64
          build-args: |
            BUILD_DATE=${{ steps.version.outputs.date }}
            BUILD_VERSION=${{ steps.version.outputs.hash }}
          target: lsubuntu

      - name: Build and push alpine
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            smhrambo/briar-mailbox:v1.0.8-alpine
            smhrambo/briar-mailbox:v1.0-alpine
            smhrambo/briar-mailbox:alpine
            smhrambo/briar-mailbox:v1.0.8-alpine3.20
            smhrambo/briar-mailbox:v1.0-alpine3.20
            smhrambo/briar-mailbox:alpine3.20
          platforms: |
            linux/amd64
            linux/arm64
          build-args: |
            BUILD_DATE=${{ steps.version.outputs.date }}
            BUILD_VERSION=${{ steps.version.outputs.hash }}
          target: alpine

      - name: Build and push debian
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            smhrambo/briar-mailbox:v1.0.8-debian
            smhrambo/briar-mailbox:v1.0-debian
            smhrambo/briar-mailbox:debian
            smhrambo/briar-mailbox:v1.0.8-bookworm
            smhrambo/briar-mailbox:v1.0-bookworm
            smhrambo/briar-mailbox:bookworm
          platforms: |
            linux/amd64
            linux/arm64
          build-args: |
            BUILD_DATE=${{ steps.version.outputs.date }}
            BUILD_VERSION=${{ steps.version.outputs.hash }}
          target: debian

      - name: Build and push ubuntu
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            smhrambo/briar-mailbox:v1.0.8-ubuntu
            smhrambo/briar-mailbox:v1.0-ubuntu
            smhrambo/briar-mailbox:ubuntu
            smhrambo/briar-mailbox:v1.0.8-noble
            smhrambo/briar-mailbox:v1.0-noble
            smhrambo/briar-mailbox:noble
          platforms: |
            linux/amd64
            linux/arm64
          build-args: |
            BUILD_DATE=${{ steps.version.outputs.date }}
            BUILD_VERSION=${{ steps.version.outputs.hash }}
          target: ubuntu
