name: Docker Image CI

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

env:
  TARGET: debian

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get current date and version
        id: version
        run: |
          echo "date=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_OUTPUT
          echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ vars.DOCKERHUB_REPO }}/${{ vars.DOCKERHUB_IMAGENAME }}
          tags: |
            type=edge,branch=main
            type=pep440,pattern={{version}}
            type=pep440,pattern={{major}}.{{minor}}
            type=sha
      
#      - name: Build and export to Docker
#        uses: docker/build-push-action@v5
#        id: build
#        with:
#          context: .
#          file: ./Dockerfile
#          load: true
#          tags: ${{ steps.meta.outputs.tags }}-${{ env.TARGET }}
#          labels: ${{ steps.meta.outputs.labels }}
#          build-args: |
#            BUILD_DATE=${{ steps.version.outputs.date }}
#            BUILD_VERSION=${{ steps.version.outputs.hash }}
#          target: ${{ env.TARGET }}
      
#      - name: Test image
#        run: |
#          docker run --rm ${{ steps.meta.outputs.tags }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}-${{ env.TARGET }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: |
            linux/amd64
            linux/arm64
          build-args: |
            BUILD_DATE=${{ steps.version.outputs.date }}
            BUILD_VERSION=${{ steps.version.outputs.hash }}
          target: ${{ env.TARGET }}
